[project]
authors = ["Lambert Moyon <lambert.moyon@helmholtz-munich.de>"]
channels = ["conda-forge", "bioconda"]
name = "parnet_demo"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.10,<3.11"
pip = ">=25.1"
ipykernel = ">=6.29,<6.30"
ipython = ">=8.37,<9.0"
numpy = ">=1.26,<2.0"
datasets = ">=3.6.0,<4.0.0"
pyarrow = ">=17.0,<21.0"
pandas = ">=2.0,<2.4"
skglm = ">=0.4,<0.5"
scipy = ">=1.15,<1.16"
sklearn-pandas = ">=2.2.0,<2.5"
scikit-learn = ">=1.7.0,<1.8.0"
#
click = ">=8.2,<9.0"
gin-config = "==0.5.0"
pyyaml = ">=6.0,<7.0"
rich = ">=14.0,<15.0"
#
transformers = ">=4.40,<5"
jaxtyping = ">=0.3.2,<0.4"
lightning = ">=2.3,<2.6"
lightning-utilities = ">=0.14,<0.15"
#
#genomekit = ">=5.0,<8.0"
biopython = ">=1.83,<1.85"
pybigwig = ">=0.3.22,<0.4"
pybedtools = ">=0.12.0,<0.13"
bedops = ">=2.4.40,<2.5"
ucsc-wigToBigWig = "*"
ucsc-bigWigToWig = "*"
ucsc-bedgraphtobigwig = "*"
#
snakemake-minimal = ">=7.28,<8.0"
pydantic = ">=2.11,<3.0"
pandera = ">=0.24,<1.0"
python-dotenv = ">=1.1,<1.5"
more-itertools = ">=10.7,<11.0"
jsonschema = ">=4.24,<5.0"
orjson = ">=3.10,<4.0"
parquet-tools = ">=0.2,<1.0"
dotmap = "*"
#
plotnine = ">=0.14,<1.0"
matplotlib = ">=3.10,<4.0"
seaborn = ">=0.13,<1.0"
logomaker = ">=0.8.6,<0.9"
viennarna = ">=2.6.0,<2.7.0"
forgi = ">=2.2.3,<3"
pyfaidx = ">=0.8.1.4,<0.9"
captum = ">=0.7.0,<0.8"
tqdm = ">=4.67.1,<5"
libopenblas = ">=0.3.29,<0.4"
umap-learn = ">=0.5.7,<0.6"

[pypi-dependencies]
jax = "==0.3.2"
protobuf = "==4.25.8"
tangermeme = { git = "git+https://github.com/jmschrei/tangermeme.git", rev = "main" }

[feature.dev.dependencies]
yamllint = ">=1.37,<1.40"
ruff = ">=0.11,<1.0"
mkdocstrings-python = ">=1.16,<2.0"
mkdocs = ">=1.6,<2.0"
mkdocs-material = ">=9.6,<10.0"
pytest = ">=8.4,<9"
pytest-cov = ">=6.0,<7.0"
pre-commit = ">=4.0,<5.0"
mypy = ">=1.11,<2.0"
pyright = ">=1.1.402,<2"

[feature.jupyter.dependencies]
jupyter = ">=1.1,<2.0"
jupyterlab = ">=4.4,<5.0"
papermill = ">=2.6,<3.0"

[feature.jupyter.pypi-dependencies]
igv-notebook = { git = "git+https://github.com/igvteam/igv-notebook.git", rev = "2995132" }

[feature.cpu.dependencies]
pytorch-cpu = "==2.5.1"

[feature.cpu.pypi-dependencies]
tensorflow = { version = ">=2.16,<2.17" }
parnet = { git = "git+https://github.com/ml4rg25-parnet/parnet.git", rev = "develop" }

[feature.gpu]
platforms = ["linux-64"]
system-requirements = { cuda = "11.8" } # NOTE: this was required for correct package resolution.

[feature.gpu.dependencies]
cuda-version = "11.8.*"
cudatoolkit = "11.8.*"
pytorch-gpu = { version = "==2.5.1", channel = "conda-forge" }

[feature.gpu.pypi-dependencies]
tensorflow = { version = ">=2.16,<2.17", extras = ["and-cuda"] }
parnet = { git = "git+https://github.com/ml4rg25-parnet/parnet.git", rev = "develop", extras = [
    "gpu",
] }

[environments]

parnet-demo = ["cpu", "jupyter", "dev"]
parnet-demo-gpu = ["gpu", "jupyter", "dev"]
