[tool.ruff]

target-version = "py310"
line-length = 120
indent-width = 4

[tool.ruff.lint]

extend-select = [
  'D', #pydocstyle
  'E', # pycodestyle
  'W', # pycodestyle warnings
  "E2", # whitespace rules
  "E4", # import rules
  "E7", # statement rules
  "E9", # runtime rules
  'F',  # Pyflakes: source file errors, unsued variables.
  'I', # sort imports
  'UP', #pyupgrade
  "RUF",  # ruff dev's own rules
  "SIM", # pyflakes simplicity
  "C90", # more complexity rules
]

ignore = [
  "E201", # whitespace after '('
  "E202", # whitespace before ')'
  "E211", # whitespace before '('
  "E203", # Whitespace before ':'
  "F401", # Remove unused imports
  #"E501", # line too long
  #"W504", # line break after binary operator
]

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = [
  "F401",  # Disable fix for unused imports (`F401`).
]


[tool.ruff.lint.pydocstyle]

convention = "google"

[tool.ruff.lint.isort]

combine-as-imports = true
split-on-trailing-comma = false

[tool.ruff.format]

quote-style = "double"  # Like Black, use double quotes for strings.
indent-style = "space"  # Like Black, indent with spaces, rather than tabs.
docstring-code-format = false  # Automatically format Python code examples in docstrings.
docstring-code-line-length = "dynamic"  # or INT


[tool.pytest.ini_options]

# See https://stackoverflow.com/questions/10253826/path-issue-with-pytest-importerror-no-module-named-yadayadayada
pythonpath = [
  "."
]
